# Generated by Django 3.1.4 on 2021-02-24 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20210214_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved', to='insta.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=True),
        ),
    ]
