# Generated by Django 3.1.4 on 2021-02-25 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20210224_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
