# Generated by Django 3.1.4 on 2021-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20210225_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='start',
        ),
    ]
