# Generated by Django 3.1.4 on 2021-02-26 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import insta.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_auto_20210225_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_picture',
            field=models.ImageField(upload_to=insta.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
