# Generated by Django 3.1.4 on 2021-03-07 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0018_chats_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='user',
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
