# Generated by Django 3.1.4 on 2021-03-17 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0020_auto_20210313_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
