# Generated by Django 3.1.4 on 2021-03-20 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0022_remove_customuser_last_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=10000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('posts', models.ManyToManyField(blank=True, null=True, related_name='posts', to='insta.Post')),
            ],
        ),
    ]
