# Generated by Django 3.1.4 on 2021-03-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import insta.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0023_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=insta.models.user_directory)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
