# Generated by Django 3.1.4 on 2021-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0024_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
