# Generated by Django 3.1.4 on 2021-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0027_auto_20210402_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
