# Generated by Django 3.1.4 on 2021-04-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0028_customuser_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
    ]
